import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { NostrEvent, NostrSigner } from '@nostrify/nostrify';
import { useCurrentUser } from '@/hooks/useCurrentUser';
import { useRelayInfo } from '@/hooks/useRelayInfo';
import { useToast } from '@/hooks/useToast';
import { queryGroupRelay, publishToGroupRelay } from '@/lib/groupRelay';
import { describeSignerError } from '@/lib/signerErrors';
import type { SignerMethod } from '@/lib/session';
import { clearSignerFailure, recordSignerFailure } from '@/lib/signerStatus';
import {
  GROUP_ADMINS,
  GROUP_CHAT,
  GROUP_MEMBERS,
  GROUP_METADATA,
  GROUP_PINS,
  GROUP_ROLES,
  GROUP_THREAD,
  JOIN_REQUEST,
  LEAVE_REQUEST,
  PUT_USER,
  REMOVE_USER,
  buildGroupTree,
  groupTags,
  isMember,
  parseGroupAdmins,
  parseGroupMembers,
  parseGroupMetadata,
  parseGroupPins,
  parseGroupRoles,
  readJoinRejection,
  type GroupMetadata,
} from '@/lib/nip29';

/**
 * Signs an event and publishes it to the group's relay, and nowhere else.
 *
 * Deliberately not `useNostrPublish`. That hook fans out to the account's
 * write relays, which for a group event is wrong twice over: the `h` tag and
 * the timeline references mean nothing anywhere else, and the spec asks those
 * relays to reject it. Shared between membership and moderation so the two
 * cannot drift apart on the point.
 */
export async function signToGroupRelay(
  user: { pubkey: string; signer: NostrSigner; method?: SignerMethod },
  relayUrl: string,
  template: { kind: number; content: string; tags: string[][] }
): Promise<NostrEvent> {
  let event: NostrEvent;

  try {
    event = await user.signer.signEvent({
      ...template,
      created_at: Math.floor(Date.now() / 1000),
    });
    clearSignerFailure(user.pubkey);
  } catch (error) {
    const problem = describeSignerError(error, { method: user.method });
    recordSignerFailure(user.pubkey, problem.kind);
    throw new Error(`${problem.title}. ${problem.description}`);
  }

  await publishToGroupRelay(relayUrl, event, AbortSignal.timeout(6000));
  return event;
}

/**
 * Whether a relay runs groups at all.
 *
 * NIP-29 needs the relay to enforce the rules — there is no client-side
 * fallback, and pointing this feature at an ordinary relay returns an empty
 * list that looks like a broken page rather than an unsupported one. The
 * relay says so in its NIP-11 document.
 */
export function useGroupRelaySupport(url: string | undefined) {
  const { data, isLoading } = useRelayInfo(url);

  return {
    supported: !!data?.supported_nips?.includes(29),
    /** Subgroups are advertised separately, under a `nip29` object. */
    subgroups:
      (data as { nip29?: { subgroups?: boolean } } | undefined)?.nip29
        ?.subgroups === true,
    info: data,
    isLoading,
  };
}

/** Every group a relay hosts, arranged into its subgroup tree. */
export function useGroups(relayUrl: string | undefined) {
  const query = useQuery({
    queryKey: ['nip29-groups', relayUrl ?? ''],
    queryFn: async ({ signal }) => {
      const events = await queryGroupRelay(
        relayUrl!,
        [{ kinds: [GROUP_METADATA], limit: 200 }],
        AbortSignal.any([signal, AbortSignal.timeout(6000)])
      );

      /**
       * Only what the relay itself signed.
       *
       * Group metadata is relay-generated by definition — the spec says
       * relays should not accept these events from anyone else. A relay that
       * does accept them would otherwise let any user publish a `kind:39000`
       * naming themselves admin of an existing group.
       */
      return events
        .map(parseGroupMetadata)
        .filter((group): group is GroupMetadata => !!group);
    },
    enabled: !!relayUrl,
    staleTime: 60_000,
  });

  const groups = query.data ?? [];

  return {
    groups,
    tree: buildGroupTree(groups),
    isLoading: query.isLoading,
    error: query.error as Error | null,
  };
}

/** One group: its metadata and everything the relay says about it. */
export function useGroup(relayUrl: string | undefined, groupId: string | undefined) {
  const query = useQuery({
    queryKey: ['nip29-group', relayUrl ?? '', groupId ?? ''],
    queryFn: async ({ signal }) => {
      const events = await queryGroupRelay(
        relayUrl!,
        [
          {
            // One request rather than five: these are all addressable events
            // on the same identifier, and relays index the `d` tag
            kinds: [
              GROUP_METADATA,
              GROUP_ADMINS,
              GROUP_MEMBERS,
              GROUP_ROLES,
              GROUP_PINS,
            ],
            '#d': [groupId!],
          },
        ],
        AbortSignal.any([signal, AbortSignal.timeout(6000)])
      );

      const of = (kind: number) => events.find((event) => event.kind === kind);
      const metadataEvent = of(GROUP_METADATA);

      return {
        metadata: metadataEvent ? parseGroupMetadata(metadataEvent) : null,
        admins: parseGroupAdmins(of(GROUP_ADMINS)),
        members: parseGroupMembers(of(GROUP_MEMBERS)),
        roles: parseGroupRoles(of(GROUP_ROLES)),
        pins: parseGroupPins(of(GROUP_PINS)),
      };
    },
    enabled: !!relayUrl && !!groupId,
    staleTime: 30_000,
  });

  return {
    group: query.data?.metadata ?? null,
    admins: query.data?.admins ?? [],
    members: query.data?.members ?? [],
    roles: query.data?.roles ?? [],
    pins: query.data?.pins ?? [],
    isLoading: query.isLoading,
    error: query.error as Error | null,
  };
}

/**
 * Messages in a group, oldest first.
 *
 * Kind 9 only. This used to ask for kind 11 as well and render both as one
 * ordered stream, which NIP-C7 forbids for exactly the reason it gives:
 * "Clients that render a 'chat view' as a stream of ordered events MUST only
 * fetch `kind 9` events in order to prevent missing context across
 * implementations." A thread is a different thing with its own replies, and
 * folding its root into the chat log shows people a message whose answers
 * live somewhere they cannot see.
 */
export function useGroupMessages(
  relayUrl: string | undefined,
  groupId: string | undefined,
  limit = 100
) {
  const query = useQuery({
    queryKey: ['nip29-messages', relayUrl ?? '', groupId ?? '', limit],
    queryFn: async ({ signal }) => {
      const events = await queryGroupRelay(
        relayUrl!,
        [{ kinds: [GROUP_CHAT], '#h': [groupId!], limit }],
        AbortSignal.any([signal, AbortSignal.timeout(6000)])
      );

      return events.sort((a, b) => a.created_at - b.created_at);
    },
    enabled: !!relayUrl && !!groupId,
    staleTime: 10_000,
    refetchInterval: 20_000,
  });

  return {
    messages: query.data ?? [],
    isLoading: query.isLoading,
  };
}

/**
 * Threads in a group, newest first.
 *
 * Split out of the chat stream rather than dropped. Kind 11 is how groups
 * carry longer posts, and a client that stopped fetching them entirely would
 * be hiding content rather than separating it.
 */
export function useGroupThreads(
  relayUrl: string | undefined,
  groupId: string | undefined,
  limit = 50
) {
  const query = useQuery({
    queryKey: ['nip29-threads', relayUrl ?? '', groupId ?? '', limit],
    queryFn: async ({ signal }) => {
      const events = await queryGroupRelay(
        relayUrl!,
        [{ kinds: [GROUP_THREAD], '#h': [groupId!], limit }],
        AbortSignal.any([signal, AbortSignal.timeout(6000)])
      );

      return events.sort((a, b) => b.created_at - a.created_at);
    },
    enabled: !!relayUrl && !!groupId,
    staleTime: 30_000,
  });

  return {
    threads: query.data ?? [],
    isLoading: query.isLoading,
  };
}

/**
 * Your standing in a group, and the two events that change it.
 *
 * Membership is read from the relay's own moderation history rather than
 * assumed from having asked: a `kind:9021` join request is a request, and in
 * a closed group it may never be answered. Showing someone as a member
 * because they clicked join would give them a composer whose every message
 * the relay rejects.
 */
export function useGroupMembership(
  relayUrl: string | undefined,
  groupId: string | undefined
) {
  const { user } = useCurrentUser();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const query = useQuery({
    queryKey: ['nip29-membership', relayUrl ?? '', groupId ?? '', user?.pubkey ?? ''],
    queryFn: async ({ signal }) => {
      const events = await queryGroupRelay(
        relayUrl!,
        [
          {
            kinds: [PUT_USER, REMOVE_USER],
            '#h': [groupId!],
            '#p': [user!.pubkey],
            limit: 50,
          },
        ],
        AbortSignal.any([signal, AbortSignal.timeout(6000)])
      );

      return isMember(events, user!.pubkey);
    },
    enabled: !!relayUrl && !!groupId && !!user,
    staleTime: 15_000,
  });

  const send = async (
    template: { kind: number; content: string; tags: string[][] }
  ) => {
    if (!user) throw new Error('Log in first');
    if (!relayUrl) throw new Error('No relay for this group');

    return await signToGroupRelay(user, relayUrl, template);
  };

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['nip29-membership'] });
    queryClient.invalidateQueries({ queryKey: ['nip29-messages'] });
  };

  const join = useMutation({
    mutationFn: async (invite?: string) =>
      send({
        kind: JOIN_REQUEST,
        content: '',
        tags: [
          ['h', groupId!],
          ...(invite ? [['code', invite]] : []),
        ],
      }),
    onSuccess: () => {
      invalidate();
      toast({
        title: 'Join request sent',
        // Honest: the relay decides, and in a closed group it may simply not
        description: 'The relay will add you if it accepts the request.',
      });
    },
    onError: (error: Error) => {
      const outcome = readJoinRejection(error.message);

      /**
       * `duplicate:` is the spec's prefix for "you are already in", which is
       * not a failure worth an error toast — it usually means our view of
       * membership is stale, so it is refreshed instead.
       */
      if (outcome === 'already-member') {
        invalidate();
        return;
      }

      /**
       * A request held for review is not a rejection either. The spec asks
       * relays to say which of the two it is, and showing "could not join" in
       * red for a request an admin is about to approve tells the user to give
       * up on something that is working.
       */
      if (outcome === 'pending') {
        toast({
          title: 'Waiting for approval',
          description: error.message,
        });
        return;
      }

      toast({
        title: 'Could not join',
        description: error.message,
        variant: 'destructive',
      });
    },
  });

  const leave = useMutation({
    mutationFn: async () =>
      send({ kind: LEAVE_REQUEST, content: '', tags: [['h', groupId!]] }),
    onSuccess: () => {
      invalidate();
      toast({ title: 'You have left the group' });
    },
    onError: (error: Error) => {
      toast({
        title: 'Could not leave',
        description: error.message,
        variant: 'destructive',
      });
    },
  });

  const post = useMutation({
    mutationFn: async ({
      content,
      seen,
      kind = GROUP_CHAT,
    }: {
      content: string;
      /** Recent messages, for the `previous` timeline references. */
      seen: NostrEvent[];
      kind?: number;
    }) =>
      send({
        kind,
        content,
        tags: groupTags(groupId!, { seen, selfPubkey: user?.pubkey }),
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['nip29-messages'] });
    },
    onError: (error: Error) => {
      toast({
        title: 'Could not send',
        description: error.message,
        variant: 'destructive',
      });
    },
  });

  return {
    isMember: query.data ?? false,
    isLoading: query.isLoading,
    join: join.mutateAsync,
    isJoining: join.isPending,
    leave: leave.mutateAsync,
    isLeaving: leave.isPending,
    post: post.mutateAsync,
    isPosting: post.isPending,
  };
}
